In [1]:
import pandas as pd

df = pd.read_csv("../data/spam.csv", encoding='latin-1')

df = df[['v1','v2']]

df.rename(columns={
    'v1':'label',
    'v2':'message'
}, inplace=True)

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df['message'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [3]:
df['message_lower'] = df['message'].str.lower()

In [4]:
df[['message','message_lower']].head()

,message,message_lower
0,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ..."
1,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...
4,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [5]:
df['num_words'] = df['message'].apply(lambda x: len(x.split()))

In [6]:
df[['message','num_words']].head()

                                             message  num_words
0  Go until jurong point, crazy.. Available only ...         20
1                      Ok lar... Joking wif u oni...          6
2  Free entry in 2 a wkly comp to win FA Cup fina...         28
3  U dun say so early hor... U c already then say...         11
4  Nah I don't think he goes to usf, he lives aro...         13

In [7]:
df.groupby('label')['num_words'].mean()

label
ham     14.200622
spam    23.851406
Name: num_words, dtype: float64

In [8]:
df.columns

Index(['label', 'message', 'message_lower', 'num_words'], dtype='object')

In [9]:
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\liza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [11]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\liza\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [12]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\liza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [13]:
word_tokenize("Hello, how are you?")

['Hello', ',', 'how', 'are', 'you', '?']

In [14]:
df['message'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [15]:
word_tokenize(df['message'][2])

['Free',
 'entry',
 'in',
 '2',
 'a',
 'wkly',
 'comp',
 'to',
 'win',
 'FA',
 'Cup',
 'final',
 'tkts',
 '21st',
 'May',
 '2005',
 '.',
 'Text',
 'FA',
 'to',
 '87121',
 'to',
 'receive',
 'entry',
 'question',
 '(',
 'std',
 'txt',
 'rate',
 ')',
 'T',
 '&',
 'C',
 "'s",
 'apply',
 '08452810075over18',
 "'s"]

In [16]:
from nltk.corpus import stopwords

nltk.download('stopwords')

stopwords.words('english')[:20]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\liza\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been']

In [17]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

sentence = "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

tokens = word_tokenize(sentence)

filtered_words = []

for word in tokens:
    if word.lower() not in stop_words:
        filtered_words.append(word)

filtered_words

['Free',
 'entry',
 '2',
 'wkly',
 'comp',
 'win',
 'FA',
 'Cup',
 'final',
 'tkts',
 '21st',
 'May',
 '2005',
 '.',
 'Text',
 'FA',
 '87121',
 'receive',
 'entry',
 'question',
 '(',
 'std',
 'txt',
 'rate',
 ')',
 '&',
 'C',
 "'s",
 'apply',
 '08452810075over18',
 "'s"]

In [18]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

print(ps.stem("playing"))
print(ps.stem("played"))
print(ps.stem("plays"))

play
play
play

In [24]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

ps = PorterStemmer()

stop_words = set(stopwords.words('english'))

def transform_text(text):

    # Lowercase
    text = text.lower()

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords
    filtered_tokens = []

    for word in tokens:
        if word not in stop_words:
            filtered_tokens.append(word)

    # Stemming
    stemmed_tokens = []

    for word in filtered_tokens:
        stemmed_tokens.append(ps.stem(word))

    return " ".join(stemmed_tokens)

In [25]:
transform_text("You have won free cash")

'free cash'

In [21]:
"won" in stop_words

True

In [26]:
df['transformed_message'] = df['message'].apply(transform_text)

In [27]:
df[['message', 'transformed_message']].head()

,message,transformed_message
0,"Go until jurong point, crazy.. Available only ...","go jurong point , crazi .. avail bugi n great ..."
1,Ok lar... Joking wif u oni...,ok lar ... joke wif u oni ...
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,U dun say so early hor... U c already then say...,u dun say earli hor ... u c alreadi say ...
4,"Nah I don't think he goes to usf, he lives aro...","nah n't think goe usf , live around though"

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidf = TfidfVectorizer(max_features=3000)

In [30]:
X = tfidf.fit_transform(df['transformed_message'])

In [31]:
X.shape

(5572, 3000)

In [32]:
tfidf.get_feature_names_out()[:20]

array(['00', '000', '008704050406', '01223585334', '02', '0207',
       '02073162414', '021', '03', '04', '05', '050703', '0578', '06',
       '07', '07123456789', '07734396839', '07742676969', '0776xxxxxxx',
       '07781482378'], dtype=object)

In [33]:
tfidf.get_feature_names_out()[100:120]

array(['09071512433', '10', '100', '1000', '100percent', '1030', '10am',
       '10k', '10p', '10ppm', '11', '113', '114', '11mth', '11mths',
       '11pm', '12', '121', '123', '1250'], dtype=object)

In [34]:
tfidf.get_feature_names_out()[500:520]

array(['blake', 'blame', 'blank', 'bless', 'block', 'bloke', 'bloo',
       'blood', 'bloodi', 'bloomberg', 'blow', 'blue', 'bluetooth', 'bmw',
       'boat', 'bodi', 'bold', 'bonu', 'boo', 'book'], dtype=object)

In [35]:
len(tfidf.get_feature_names_out())

3000

In [36]:
X[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 3000))

In [37]:
y = df['label']

In [38]:
y.head()

0     ham
1     ham
2    spam
3     ham
4     ham
Name: label, dtype: object

In [39]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [40]:
y[:5]

array([0, 0, 1, 0, 0])

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [43]:
print(X_train.shape)
print(X_test.shape)

(4457, 3000)
(1115, 3000)

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
model = MultinomialNB()

In [46]:
model.fit(X_train, y_train)

MultinomialNB()

In [47]:
y_pred = model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9775784753363229

In [49]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[965,   0],
       [ 25, 125]])

In [50]:
from sklearn.metrics import precision_score

precision_score(y_test, y_pred)

1.0

In [51]:
from sklearn.metrics import recall_score

recall_score(y_test, y_pred)

0.8333333333333334

In [52]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       965
           1       1.00      0.83      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115